import React, { useState, useRef, useCallback, useMemo, useEffect } from 'react';
import { 
  Upload, 
  Search, 
  Trash2, 
  Copy, 
  Check, 
  Info, 
  Sparkles, 
  Flame, 
  RefreshCw, 
  ArrowLeft, 
  Download, 
  CheckCircle2, 
  Terminal, 
  Grid, 
  FileCode,
  X,
  FileCheck2,
  Binary
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

// Define SearchResult structure for display (strictly matching requirements)
interface FeatureResult {
  featureName: string;
  rva: string;
}

// Predefined Smart Feature Mapping database
const SMART_MAPPINGS = [
  { func: "IsHighFPS120Open", feature: "120 FPS Unlocker", type: "bool" },
  { func: "get_CanBeLockedByAimAssist", feature: "Aim Assist", type: "bool" },
  { func: "SetAimRotation", feature: "Aimbot Use", type: "void" },
  { func: "SyncWeaponAmmoInClip", feature: "Ammo In Clip", type: "void" },
  { func: "SetupModule", feature: "Black Body", type: "void" },
  { func: "get_IsSwimSurf", feature: "Camera Hack", type: "bool" },
  { func: "get_OffsetForNormal", feature: "Camera View (Zoom Out)", type: "float" },
  { func: "get_UserGems", feature: "Diamond Hack", type: "int" },
  { func: "GetDisableFriendSpectateSetting", feature: "Disable Spectate", type: "bool" },
  { func: "ADBBMDMEFNO", feature: "Double Gun", type: "bool" },
  { func: "get_FSModeUseMedikitFasterRate", feature: "Fast Blood Wrap", type: "float" },
  { func: "get_InSwapWeaponCD", feature: "Fast Gun", type: "float" },
  { func: "get_FSModeUseMedikitFasterRate", feature: "Fast Medkit (2.25s)", type: "float" },
  { func: "get_FastAutoReloadSpeed", feature: "Fast Reload", type: "float" },
  { func: "OnStartChangeWeapon", feature: "Fast Weapon Switch", type: "void" },
  { func: "IsFemale", feature: "Female Model Hack", type: "bool" },
  { func: "AOCFOHFIAAM", feature: "Fix Crash", type: "bool" },
  { func: "BNFAGNBHHIF", feature: "Ghost Hack", type: "bool" },
  { func: "EAGIPMCDBIF", feature: "Ghost Hack 2", type: "bool" },
  { func: "get_IsGod", feature: "Gold Body", type: "bool" },
  { func: "get_UserCoins", feature: "Gold Hack", type: "int" },
  { func: "get_fog", feature: "HD Map / No Fog", type: "float" },
  { func: "get_MaxJumpHeight", feature: "High Jump", type: "float" },
  { func: "IsOnlineGame", feature: "Lobby Kill", type: "bool" },
  { func: "OnPreparationCancel", feature: "Medkit Run", type: "void" },
  { func: "IsFreeMove", feature: "Movement Shoot", type: "bool" },
  { func: "IsPlayerReadyNeedDelay", feature: "No Delay", type: "bool" },
  { func: "GetScatterRate", feature: "No Recoil", type: "float" },
  { func: "IsSightingUIAvailable", feature: "No Scope", type: "bool" },
  { func: "get_IsSpecialName", feature: "NPC Name", type: "bool" },
  { func: "get_ResetGuest", feature: "Reset Guest", type: "bool" },
  { func: "IsFreeMove", feature: "Run & Shoot", type: "bool" },
  { func: "RequestStartSwimmingSurfing", feature: "Run Under Water", type: "bool" },
  { func: "GetWeaponRunSpeedScale", feature: "Speed Hack", type: "float" },
  { func: "LHGGPDLOPAH", feature: "Teleport Kill", type: "bool" },
  { func: "get_IsAmmoFree", feature: "Unlimited Ammo", type: "bool" },
  { func: "IsUnlimitedGloowall", feature: "Unlimited Gloo Wall", type: "bool" },
  { func: "IsUnlimitedThrowables", feature: "Unlimited Grenades", type: "bool" },
  { func: "IsCelebrity", feature: "V Badge", type: "bool" },
  { func: "UseHighQualityAvatar", feature: "White Body", type: "void" },
  { func: "MoveNext", feature: "White Body", type: "bool" }
];

// Extract unique features
const UNIQUE_FEATURES = Array.from(new Set(SMART_MAPPINGS.map(m => m.feature))).sort();

interface IntPatchValue {
  decimal: string;
  hex: string;
}

const INT_PATCH_VALUES: IntPatchValue[] = [
  { decimal: "100", hex: "64 00 AA E3 1E FF 2F E1" },
  { decimal: "255", hex: "FF 00 AA E3 1E FF 2F E1" },
  { decimal: "999", hex: "E7 03 00 E3 1E FF 2F E1" }
];

interface FloatPatchValue {
  value: string;
  hex: string;
}

const FLOAT_PATCH_VALUES: FloatPatchValue[] = [
  { value: "1000.0", hex: "00 00 7A 44 1E FF 2F E1" },
  { value: "1.0", hex: "00 00 80 3F 1E FF 2F E1" },
  { value: "0.5", hex: "00 00 00 3F 1E FF 2F E1" },
  { value: "2.0", hex: "00 00 00 40 1E FF 2F E1" }
];

// Predefined mock dump.cs for local sandbox demonstration
const SAMPLE_DUMP_CS = `// Generated by Il2CppDumper v6.4.15
// Namespace: 
public class GameManager : MonoBehaviour
{
	// RVA: 0x7F17870 Offset: 0x7F17870 VA: 0xACF8D870
	public static bool IsHighFPS120Open() { }

	// RVA: 0x521B780 Offset: 0x521B780 VA: 0xBC1122
	private int get_UserCoins() { }

	// RVA: 0x1A2B3C4 Offset: 0x1A2B3C4 VA: 0xDEB001
	public bool get_CanBeLockedByAimAssist() { }
}

public class WeaponManager : MonoBehaviour
{
	// RVA: 0xFB1374 Offset: 0xFB1374 VA: 0x9F8E7D
	public float get_InSwapWeaponCD() { }

	// RVA: 0x334455 Offset: 0x334455 VA: 0x77334455
	private bool ADBBMDMEFNO() { }

	// RVA: 0xAB9988 Offset: 0xAB9988 VA: 0x88AB9988
	public float get_fog() { }
}
`;

// Extract a single function block completely, including preceding comments and multi-line body
const extractFullFunction = (content: string, funcName: string, targetRva?: string): string => {
  if (!content || !funcName) return '';
  const contentLower = content.toLowerCase();
  const funcLower = funcName.toLowerCase();
  const funcLen = funcName.length;
  
  let index = 0;
  let bestFallback = '';

  while (true) {
    index = contentLower.indexOf(funcLower, index);
    if (index === -1) break;
    
    // Check word boundaries
    const prevChar = index > 0 ? content[index - 1] : '';
    const nextChar = index + funcLen < content.length ? content[index + funcLen] : '';
    const isWordCharBefore = /[a-zA-Z0-9_]/.test(prevChar);
    const isWordCharAfter = /[a-zA-Z0-9_]/.test(nextChar);
    
    if (!isWordCharBefore && !isWordCharAfter) {
      // Find the start of the line where funcName is declared
      let lineStart = content.lastIndexOf('\n', index);
      lineStart = lineStart === -1 ? 0 : lineStart + 1;
      
      // Find preceding comments (RVA lines)
      let firstCommentLineStart = lineStart;
      let scanIndex = lineStart;
      let linesChecked = 0;
      const maxBackwardLines = 15;
      
      while (scanIndex > 0 && linesChecked < maxBackwardLines) {
        const prevNewline = content.lastIndexOf('\n', scanIndex - 2);
        const prevLineStart = prevNewline === -1 ? 0 : prevNewline + 1;
        const prevLine = content.substring(prevLineStart, scanIndex).trim();
        linesChecked++;
        
        if (prevLine.startsWith('//')) {
          firstCommentLineStart = prevLineStart;
        } else if (prevLine === '' || prevLine.includes('class ') || prevLine.includes('struct ') || prevLine.includes('{') || prevLine.includes('}')) {
          break;
        } else {
          break;
        }
        scanIndex = prevLineStart;
      }
      
      // Now find the end of the function
      let lineEnd = content.indexOf('\n', index);
      if (lineEnd === -1) lineEnd = content.length;
      
      const signatureLine = content.substring(lineStart, lineEnd);
      let extractedBlock = '';
      
      // If it's inline `{ }`
      if (signatureLine.includes('{') && signatureLine.includes('}')) {
        extractedBlock = content.substring(firstCommentLineStart, lineEnd).trim();
      } else {
        // Multi-line scan
        let braceCount = 0;
        let foundBrace = false;
        let scanForwardIndex = lineStart;
        let forwardLinesCount = 0;
        let finalEndIndex = lineEnd;
        
        while (scanForwardIndex < content.length && forwardLinesCount < 30) {
          const nextNewline = content.indexOf('\n', scanForwardIndex);
          const currentLineEnd = nextNewline === -1 ? content.length : nextNewline;
          const currentLine = content.substring(scanForwardIndex, currentLineEnd);
          
          for (let i = 0; i < currentLine.length; i++) {
            const char = currentLine[i];
            if (char === '{') {
              braceCount++;
              foundBrace = true;
            } else if (char === '}') {
              braceCount--;
            }
          }
          
          finalEndIndex = currentLineEnd;
          if (foundBrace && braceCount === 0) {
            break;
          }
          
          if (nextNewline === -1) break;
          scanForwardIndex = nextNewline + 1;
          forwardLinesCount++;
        }
        extractedBlock = content.substring(firstCommentLineStart, finalEndIndex).trim();
      }

      if (extractedBlock) {
        // If targetRva is specified and this block matches it, return immediately
        if (targetRva && targetRva !== 'Not Found') {
          if (extractedBlock.includes(targetRva)) {
            return extractedBlock;
          }
        }
        
        if (!bestFallback) {
          bestFallback = extractedBlock;
        }
      }
    }
    
    index += funcLen;
  }
  
  return bestFallback;
};

// Find the correct function body even if a feature has multiple mapping functions
const getFunctionBodyForFeature = (feature: string, rva: string, fileContent: string): { body: string; funcName: string } => {
  const mappings = SMART_MAPPINGS.filter(m => m.feature === feature);
  
  // Try to match the function that contains the target RVA
  for (const mapping of mappings) {
    const body = extractFullFunction(fileContent, mapping.func, rva);
    if (body && rva && rva !== 'Not Found' && body.includes(rva)) {
      return { body, funcName: mapping.func };
    }
  }
  
  // Fallback to any matching function signature
  for (const mapping of mappings) {
    const body = extractFullFunction(fileContent, mapping.func);
    if (body) {
      return { body, funcName: mapping.func };
    }
  }
  
  return { body: '', funcName: '' };
};

// C# Token-based syntax highlighter for code display
const highlightCSharp = (code: string): React.ReactNode => {
  if (!code) return null;
  const lines = code.split('\n');
  
  return lines.map((line, lineIdx) => {
    const trimmed = line.trim();
    if (trimmed.startsWith('//')) {
      return (
        <div key={lineIdx} className="text-slate-500 italic">
          {line}
        </div>
      );
    }
    
    // Regex split to capture words, spaces, symbols
    const tokens = line.split(/(\s+|[{}();,])/);
    
    return (
      <div key={lineIdx} className="text-slate-300">
        {tokens.map((token, tokenIdx) => {
          const trimmedToken = token.trim();
          if (!trimmedToken) {
            return <span key={tokenIdx}>{token}</span>;
          }
          
          if (['public', 'private', 'protected', 'internal'].includes(trimmedToken)) {
            return <span key={tokenIdx} className="text-rose-400 font-semibold">{token}</span>;
          }
          if (['static', 'virtual', 'override', 'readonly', 'const'].includes(trimmedToken)) {
            return <span key={tokenIdx} className="text-amber-400">{token}</span>;
          }
          if (['bool', 'int', 'float', 'double', 'void', 'string', 'class', 'struct'].includes(trimmedToken)) {
            return <span key={tokenIdx} className="text-emerald-400 font-medium">{token}</span>;
          }
          if (trimmedToken.startsWith('0x') || /^\d+$/.test(trimmedToken)) {
            return <span key={tokenIdx} className="text-blue-400">{token}</span>;
          }
          if (trimmedToken.startsWith('//')) {
            return <span key={tokenIdx} className="text-slate-500 italic">{token}</span>;
          }
          
          return <span key={tokenIdx}>{token}</span>;
        })}
      </div>
    );
  });
};

export default function App() {
  const [activeTab, setActiveTab] = useState<'mapper' | 'hexViewer'>('mapper');

  // Hex Viewer States
  const [hexFile, setHexFile] = useState<File | null>(null);
  const [hexFileName, setHexFileName] = useState<string>('');
  const [hexFileSize, setHexFileSize] = useState<number>(0);
  const [hexUploadSuccess, setHexUploadSuccess] = useState<boolean>(false);
  const [hexOffsetInput, setHexOffsetInput] = useState<string>('');
  const [hexBytes, setHexBytes] = useState<Uint8Array | null>(null);
  const [hexError, setHexError] = useState<string>('');
  const [isHexDragging, setIsHexDragging] = useState<boolean>(false);
  const [hexCopiedFeedback, setHexCopiedFeedback] = useState<string | null>(null);

  // Navigation & File States
  const [view, setView] = useState<'upload' | 'scanning' | 'results'>('upload');
  const [fileContent, setFileContent] = useState<string>('');
  const [fileName, setFileName] = useState<string>('');
  const [fileSize, setFileSize] = useState<number>(0);
  const [lineCount, setLineCount] = useState<number>(0);
  const [isDemo, setIsDemo] = useState<boolean>(false);

  // Scanning states
  const [isBulkScanning, setIsBulkScanning] = useState<boolean>(false);
  const [bulkScanProgress, setBulkScanProgress] = useState<number>(0);
  const [bulkScanResults, setBulkScanResults] = useState<Record<string, string>>({});
  const [bulkScanTime, setBulkScanTime] = useState<number>(0);
  const [hasRunBulkScan, setHasRunBulkScan] = useState<boolean>(false);

  // UI display & filter states
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [resultsLayout, setResultsLayout] = useState<'cards' | 'plain'>('cards');
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>('');

  // Modal / Details Panel states
  const [selectedFeatureForModal, setSelectedFeatureForModal] = useState<string | null>(null);
  const [modalFunctionBody, setModalFunctionBody] = useState<string>('');
  const [modalRva, setModalRva] = useState<string>('');
  const [modalType, setModalType] = useState<string>('');
  const [modalFuncName, setModalFuncName] = useState<string>('');
  const [modalCopiedType, setModalCopiedType] = useState<string | null>(null);
  const [intSearchQuery, setIntSearchQuery] = useState<string>('');
  const [floatSearchQuery, setFloatSearchQuery] = useState<string>('');

  const filteredIntPatchValues = useMemo(() => {
    const query = intSearchQuery.trim().toLowerCase();
    if (!query) return INT_PATCH_VALUES;
    return INT_PATCH_VALUES.filter(
      (item) =>
        item.decimal.toLowerCase().includes(query) ||
        item.decimal.replace(/,/g, '').includes(query)
    );
  }, [intSearchQuery]);

  const filteredFloatPatchValues = useMemo(() => {
    const query = floatSearchQuery.trim().toLowerCase();
    if (!query) return FLOAT_PATCH_VALUES;
    return FLOAT_PATCH_VALUES.filter(
      (item) =>
        item.value.toLowerCase().includes(query)
    );
  }, [floatSearchQuery]);

  useEffect(() => {
    if (!selectedFeatureForModal) {
      setIntSearchQuery('');
      setFloatSearchQuery('');
    }
  }, [selectedFeatureForModal]);

  useEffect(() => {
    // 1. Disable right-click context menu
    const handleContextMenu = (e: MouseEvent) => {
      e.preventDefault();
    };
    document.addEventListener('contextmenu', handleContextMenu);

    // 2. Disable common shortcuts (Ctrl+U, Ctrl+S, Ctrl+Shift+I, Ctrl+Shift+J, Ctrl+Shift+C, F12)
    const handleKeyDown = (e: KeyboardEvent) => {
      const isCtrlOrMeta = e.ctrlKey || e.metaKey;
      
      // Ctrl+U
      if (isCtrlOrMeta && (e.key === 'u' || e.key === 'U' || e.keyCode === 85)) {
        e.preventDefault();
        return;
      }
      // Ctrl+S
      if (isCtrlOrMeta && (e.key === 's' || e.key === 'S' || e.keyCode === 83)) {
        e.preventDefault();
        return;
      }
      // Ctrl+Shift+I / J / C
      if (isCtrlOrMeta && e.shiftKey && (
        e.key === 'I' || e.key === 'i' || e.keyCode === 73 ||
        e.key === 'J' || e.key === 'j' || e.keyCode === 74 ||
        e.key === 'C' || e.key === 'c' || e.keyCode === 67
      )) {
        e.preventDefault();
        return;
      }
      // F12
      if (e.key === 'F12' || e.keyCode === 123) {
        e.preventDefault();
        return;
      }
    };
    document.addEventListener('keydown', handleKeyDown);

    return () => {
      document.removeEventListener('contextmenu', handleContextMenu);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, []);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Buffer lines count helper
  const countLines = (text: string): number => {
    let count = 1;
    let pos = 0;
    while ((pos = text.indexOf('\n', pos)) !== -1) {
      count++;
      pos++;
    }
    return count;
  };

  // Perform the physical, lightning-fast scan
  const executePhysicalScan = useCallback((content: string): { results: Record<string, string>; duration: number } => {
    const startTime = performance.now();
    const results: Record<string, string> = {};
    const contentLower = content.toLowerCase();
    const contentLen = content.length;

    UNIQUE_FEATURES.forEach((feature) => {
      // Find the corresponding mappings for this feature
      const mappings = SMART_MAPPINGS.filter(m => m.feature === feature);
      let foundRVA = 'Not Found';

      for (const mapping of mappings) {
        const funcName = mapping.func;
        const funcLower = funcName.toLowerCase();
        const funcLen = funcName.length;
        let index = 0;

        while (true) {
          index = contentLower.indexOf(funcLower, index);
          if (index === -1) break;

          // Verify whole word boundaries
          const prevChar = index > 0 ? content[index - 1] : '';
          const nextChar = index + funcLen < contentLen ? content[index + funcLen] : '';
          const isWordCharBefore = /[a-zA-Z0-9_]/.test(prevChar);
          const isWordCharAfter = /[a-zA-Z0-9_]/.test(nextChar);

          if (!isWordCharBefore && !isWordCharAfter) {
            // Found matching identifier, now find its preceding // RVA: line
            let lineStart = content.lastIndexOf('\n', index);
            lineStart = lineStart === -1 ? 0 : lineStart + 1;

            let scanIndex = lineStart;
            let rvaLine = '';
            let linesChecked = 0;
            const maxBackwardLines = 10;

            while (scanIndex > 0 && linesChecked < maxBackwardLines) {
              let prevNewline = content.lastIndexOf('\n', scanIndex - 2);
              let prevLineStart = prevNewline === -1 ? 0 : prevNewline + 1;
              let prevLine = content.substring(prevLineStart, scanIndex).trim();
              linesChecked++;

              if (prevLine.startsWith('// RVA:')) {
                rvaLine = prevLine;
                break;
              }
              if (prevLine.includes('class ') || prevLine.includes('struct ') || prevLine.includes('{') || prevLine.includes('}')) {
                break;
              }
              scanIndex = prevLineStart;
            }

            if (rvaLine) {
              const rvaMatch = rvaLine.match(/RVA:\s*(0x[0-9A-Fa-f]+)/i);
              if (rvaMatch) {
                foundRVA = rvaMatch[1];
                break; // Found matching RVA, skip further instances
              }
            }
          }
          index += funcLen;
        }

        if (foundRVA !== 'Not Found') {
          break; // Found the value, skip remaining alternate method signatures
        }
      }

      results[feature] = foundRVA;
    });

    const endTime = performance.now();
    return {
      results,
      duration: Math.round(endTime - startTime)
    };
  }, []);

  // Integrated, premium animated scanner controller
  const startScanningProcess = useCallback((content: string, name: string, size: number, isSample: boolean = false) => {
    setFileContent(content);
    setFileName(name);
    setFileSize(size);
    setLineCount(countLines(content));
    setIsDemo(isSample);
    setErrorMessage('');

    // Trigger visual loading screen
    setView('scanning');
    setBulkScanProgress(0);
    setIsBulkScanning(true);

    let progress = 0;
    const interval = setInterval(() => {
      progress += Math.floor(Math.random() * 8) + 4;
      if (progress >= 100) {
        progress = 100;
        clearInterval(interval);

        // Run actual heavy-duty parsing
        const scan = executePhysicalScan(content);

        setTimeout(() => {
          setBulkScanResults(scan.results);
          setBulkScanTime(scan.duration);
          setIsBulkScanning(false);
          setHasRunBulkScan(true);
          setView('results');
        }, 400); // Breathe at 100% for transition smoothness
      } else {
        setBulkScanProgress(progress);
      }
    }, 45); // Completes loading screen sequence in ~1 second
  }, [executePhysicalScan]);

  // Handle uploaded/dragged files
  const handleFile = (file: File) => {
    if (!file.name.endsWith('.cs') && !file.name.endsWith('.txt')) {
      setErrorMessage('Please upload a valid Unity dump.cs or text file.');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const text = e.target?.result as string;
      startScanningProcess(text, file.name, file.size);
    };
    reader.onerror = () => {
      setErrorMessage('Failed to read file. Please try again.');
    };
    reader.readAsText(file);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      handleFile(e.target.files[0]);
    }
  };

  // Drag-and-drop mechanics
  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      handleFile(e.dataTransfer.files[0]);
    }
  };

  const triggerFileBrowser = () => {
    fileInputRef.current?.click();
  };

  // Sandbox demonstration builder
  const loadSandboxTemplate = () => {
    startScanningProcess(SAMPLE_DUMP_CS, 'sandbox_dump.cs', SAMPLE_DUMP_CS.length, true);
  };

  // Hex Viewer Event Handlers and Helpers
  const hexFileInputRef = useRef<HTMLInputElement>(null);

  const triggerHexFileBrowser = () => {
    hexFileInputRef.current?.click();
  };

  const handleHexFile = (file: File) => {
    setHexFile(file);
    setHexFileName(file.name);
    setHexFileSize(file.size);
    setHexUploadSuccess(true);
    setHexBytes(null);
    setHexError('');
  };

  const handleHexFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      handleHexFile(e.target.files[0]);
    }
  };

  const handleHexDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsHexDragging(true);
  };

  const handleHexDragLeave = () => {
    setIsHexDragging(false);
  };

  const handleHexDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsHexDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      handleHexFile(e.dataTransfer.files[0]);
    }
  };

  const handleReadHex = () => {
    setHexError('');
    setHexBytes(null);

    if (!hexFile) {
      setHexError('No file selected');
      return;
    }

    let offsetStr = hexOffsetInput.trim();
    if (offsetStr.toLowerCase().startsWith('0x')) {
      offsetStr = offsetStr.substring(2);
    }

    if (!offsetStr) {
      setHexError('Invalid Offset');
      return;
    }

    // Parse hexadecimal offset
    const offset = parseInt(offsetStr, 16);
    if (isNaN(offset) || !/^[0-9A-Fa-f]+$/.test(offsetStr)) {
      setHexError('Invalid Offset');
      return;
    }

    if (offset < 0 || offset >= hexFile.size) {
      setHexError('Offset outside file');
      return;
    }

    // Read exactly 128 bytes
    const blobSlice = hexFile.slice(offset, Math.min(offset + 128, hexFile.size));
    const reader = new FileReader();
    reader.onload = (e) => {
      if (e.target?.result instanceof ArrayBuffer) {
        setHexBytes(new Uint8Array(e.target.result));
      } else {
        setHexError('Failed to read file segment');
      }
    };
    reader.onerror = () => {
      setHexError('Failed to read file segment');
    };
    reader.readAsArrayBuffer(blobSlice);
  };

  const handleHexClear = () => {
    setHexFile(null);
    setHexFileName('');
    setHexFileSize(0);
    setHexUploadSuccess(false);
    setHexOffsetInput('');
    setHexBytes(null);
    setHexError('');
  };

  const handleCopySelectedHex = () => {
    const selectionText = window.getSelection()?.toString();
    if (!selectionText) {
      setHexError('Please highlight some bytes in the output first');
      setTimeout(() => setHexError(''), 3000);
      return;
    }
    
    const cleaned = selectionText.trim().split(/\s+/).filter(Boolean).join(' ');
    
    if (cleaned) {
      navigator.clipboard.writeText(cleaned);
      setHexCopiedFeedback('selected');
      setTimeout(() => setHexCopiedFeedback(null), 1500);
    }
  };

  const handleCopyAllHex = () => {
    if (!hexBytes) return;
    const formatted = Array.from(hexBytes)
      .map((b: number) => b.toString(16).padStart(2, '0').toUpperCase())
      .join(' ');
    
    navigator.clipboard.writeText(formatted);
    setHexCopiedFeedback('all');
    setTimeout(() => setHexCopiedFeedback(null), 1500);
  };

  const formattedHexFileSize = useMemo(() => {
    if (hexFileSize === 0) return '0.0 KB';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(hexFileSize) / Math.log(k));
    return parseFloat((hexFileSize / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
  }, [hexFileSize]);

  const formattedHexRows = useMemo(() => {
    if (!hexBytes) return [];
    const rows = [];
    for (let i = 0; i < hexBytes.length; i += 16) {
      const slice = hexBytes.slice(i, i + 16);
      const rowStr = Array.from(slice)
        .map((b: number) => b.toString(16).padStart(2, '0').toUpperCase())
        .join(' ');
      rows.push(rowStr);
    }
    return rows;
  }, [hexBytes]);

  // State Clear / Back reset
  const handleClear = () => {
    setFileContent('');
    setFileName('');
    setFileSize(0);
    setLineCount(0);
    setBulkScanResults({});
    setHasRunBulkScan(false);
    setSearchQuery('');
    setErrorMessage('');
    setIsDemo(false);
    setView('upload');
  };

  // Format File Size
  const formattedFileSize = useMemo(() => {
    if (fileSize === 0) return '0.0 KB';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB'];
    const i = Math.floor(Math.log(fileSize) / Math.log(k));
    return parseFloat((fileSize / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
  }, [fileSize]);

  // Output Plaintext builder (Exactly [FUNCTION NAME]                 [RVA])
  const getFormattedResultsText = useCallback((filterText: string = '') => {
    let output = `[FUNCTION NAME]`.padEnd(32, ' ') + `[RVA]\n`;
    output += `------------------------------------------------\n`;

    const filtered = UNIQUE_FEATURES.filter(f => {
      const rva = bulkScanResults[f] || 'Not Found';
      const isFound = rva !== 'Not Found';
      return isFound && f.toLowerCase().includes(filterText.toLowerCase());
    });

    filtered.forEach((feature) => {
      const rva = bulkScanResults[feature];
      const mapping = SMART_MAPPINGS.find(m => m.feature === feature);
      const typeStr = mapping ? ` (${mapping.type.toUpperCase()})` : '';
      output += `${feature.padEnd(32, ' ')}${rva}${typeStr}\n`;
    });

    return output;
  }, [bulkScanResults]);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 1500);
  };

  // Filtered features for card grid listing (only show found features)
  const filteredFeatures = useMemo(() => {
    return UNIQUE_FEATURES.filter(f => {
      const rva = bulkScanResults[f] || 'Not Found';
      const isFound = rva !== 'Not Found';
      return isFound && f.toLowerCase().includes(searchQuery.toLowerCase());
    });
  }, [searchQuery, bulkScanResults]);

  return (
    <div className="min-h-screen bg-[#08080c] text-slate-100 font-sans flex flex-col selection:bg-red-500/30 selection:text-red-200 select-none">
      
      {/* Decorative Top Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-[120px] bg-red-600/10 blur-[100px] pointer-events-none rounded-full" />

      {/* Header bar */}
      <header className="border-b border-red-950/40 bg-[#0d0d12]/80 backdrop-blur-md sticky top-0 z-40 py-4.5 px-6 shadow-[0_1px_15px_rgba(0,0,0,0.4)]">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-tr from-red-600 to-red-500 rounded-xl flex items-center justify-center shadow-[0_0_20px_rgba(239,68,68,0.35)] transition-transform duration-300 hover:scale-105">
              <Flame className="w-5.5 h-5.5 text-white" />
            </div>
            <div>
              <h1 className="text-xl font-bold tracking-widest text-white font-display uppercase">
                INTERNAL X CHEATS
              </h1>
              <p className="text-[10px] text-red-500 uppercase tracking-widest font-bold">DUMP.CS RVA MAPPER</p>
            </div>
          </div>

          <div className="flex items-center gap-4">
            {view === 'results' && (
              <button
                onClick={handleClear}
                className="px-3.5 py-1.5 border border-red-500/20 hover:border-red-500/40 bg-red-950/10 hover:bg-red-950/30 text-red-400 hover:text-red-300 rounded-xl text-xs font-semibold tracking-wider font-display transition-all cursor-pointer flex items-center gap-1.5"
              >
                <ArrowLeft className="w-3.5 h-3.5" /> BACK TO UPLOAD
              </button>
            )}
            <div className="flex flex-col items-end border-l border-slate-800 pl-4">
              <span className="text-[9px] text-slate-500 uppercase tracking-wider">Engine status</span>
              {fileContent ? (
                <span className="text-[11px] font-mono text-red-500 flex items-center gap-1.5 font-bold">
                  <span className="w-2 h-2 rounded-full bg-red-500 shadow-[0_0_8px_#EF4444] animate-pulse" /> BUFFER LOGGED
                </span>
              ) : (
                <span className="text-[11px] font-mono text-slate-600 flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full bg-slate-800" /> IDLE SYSTEM
                </span>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* Subheader / Tabs Bar */}
      <div className="border-b border-red-950/20 bg-[#09090d]/60 backdrop-blur-md py-2.5 px-6 relative z-30">
        <div className="max-w-7xl mx-auto flex items-center gap-2">
          <button
            onClick={() => setActiveTab('mapper')}
            className={`px-4 py-2 rounded-xl text-xs font-bold tracking-wider font-display uppercase transition-all flex items-center gap-2 cursor-pointer ${
              activeTab === 'mapper'
                ? 'bg-red-500/10 border border-red-500/30 text-red-400 shadow-[0_0_15px_rgba(239,68,68,0.05)]'
                : 'border border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Flame className="w-4 h-4 shrink-0" />
            <span>DUMP.CS RVA MAPPER</span>
          </button>
          <button
            onClick={() => setActiveTab('hexViewer')}
            className={`px-4 py-2 rounded-xl text-xs font-bold tracking-wider font-display uppercase transition-all flex items-center gap-2 cursor-pointer ${
              activeTab === 'hexViewer'
                ? 'bg-red-500/10 border border-red-500/30 text-red-400 shadow-[0_0_15px_rgba(239,68,68,0.05)]'
                : 'border border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Binary className="w-4 h-4 shrink-0" />
            <span>LIBIL2CPP HEX VIEWER</span>
          </button>
        </div>
      </div>

      {/* Main stage */}
      <main className="flex-grow max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 flex flex-col justify-center">
        
        <AnimatePresence mode="wait">

          {/* VIEW 1: UPLOAD SCREEN */}
          {activeTab === 'mapper' && view === 'upload' && (
            <motion.div
              key="upload-view"
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -15 }}
              transition={{ duration: 0.25, ease: 'easeOut' }}
              className="max-w-2xl w-full mx-auto"
            >
              <div 
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
                className={`bg-[#0d0d14]/90 backdrop-blur-xl border rounded-3xl p-8 text-center relative overflow-hidden transition-all duration-300 shadow-2xl ${
                  isDragging 
                    ? 'border-red-500 bg-red-500/5 shadow-[0_0_40px_rgba(239,68,68,0.15)]Scale scale-[1.01]' 
                    : 'border-red-950/30 hover:border-red-500/20'
                }`}
              >
                {/* Dragging state overlay */}
                <div className={`absolute inset-0 bg-[#08080c]/90 z-20 flex flex-col items-center justify-center transition-opacity duration-300 pointer-events-none ${isDragging ? 'opacity-100' : 'opacity-0'}`}>
                  <Upload className="w-14 h-14 text-red-500 mb-3 animate-bounce" />
                  <p className="text-base font-bold text-red-400 font-display">Drop your dump.cs file here</p>
                  <p className="text-xs text-slate-500 mt-1">Release to start instant automatic mapper scan</p>
                </div>

                <div className="w-16 h-16 bg-red-950/20 border border-red-500/20 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-[0_0_15px_rgba(239,68,68,0.1)]">
                  <Upload className="w-7 h-7 text-red-500" />
                </div>

                <h2 className="text-2xl font-bold tracking-tight text-white mb-2 font-display">
                  Analyze Unity <span className="text-red-500">dump.cs</span> Offsets
                </h2>
                
                <p className="text-sm text-slate-400 max-w-md mx-auto leading-relaxed mb-8">
                  Upload your C# class dump file to automatically extract RVA values for predefined features. Everything is processed 100% locally inside your web browser.
                </p>

                {errorMessage && (
                  <div className="mb-6 p-3 bg-red-500/10 border border-red-500/20 rounded-xl text-red-400 text-xs font-semibold flex items-center justify-center gap-2">
                    <X className="w-4 h-4 shrink-0 cursor-pointer" onClick={() => setErrorMessage('')} />
                    <span>{errorMessage}</span>
                  </div>
                )}

                <div className="flex justify-center">
                  <button
                    onClick={triggerFileBrowser}
                    className="w-full sm:w-auto px-8 py-4 bg-gradient-to-r from-red-600 to-red-500 hover:from-red-500 hover:to-red-400 text-white font-bold font-display text-xs rounded-xl shadow-[0_0_20px_rgba(239,68,68,0.3)] hover:shadow-[0_0_25px_rgba(239,68,68,0.45)] hover:scale-[1.02] transition-all cursor-pointer uppercase tracking-wider"
                  >
                    SELECT DUMP.CS FILE
                  </button>
                </div>

                <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleFileChange} 
                  accept=".cs,.txt" 
                  className="hidden" 
                />

                <div className="mt-8 pt-6 border-t border-red-950/20 flex items-center justify-center gap-8 text-[11px] text-slate-500 font-mono uppercase">
                  <span className="flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5 text-red-500/60" /> BROWSER PERSISTENT
                  </span>
                  <span className="flex items-center gap-1.5">
                    <CheckCircle2 className="w-3.5 h-3.5 text-red-500/60" /> 100% OFFLINE SECURE
                  </span>
                </div>
              </div>
            </motion.div>
          )}

          {/* VIEW 2: PREMIUM LOADING / SCANNING SCREEN */}
          {activeTab === 'mapper' && view === 'scanning' && (
            <motion.div
              key="scanning-view"
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="max-w-md w-full mx-auto text-center"
            >
              <div className="bg-[#0d0d14]/90 backdrop-blur-xl border border-red-500/10 rounded-3xl p-10 shadow-2xl relative">
                
                {/* Glowing Spinner */}
                <div className="relative w-20 h-20 mx-auto mb-8">
                  <div className="absolute inset-0 rounded-full border-4 border-red-950/30"></div>
                  <div className="absolute inset-0 rounded-full border-4 border-t-red-500 border-r-red-500/40 animate-spin"></div>
                  <div className="absolute inset-2 bg-[#08080c] rounded-full flex items-center justify-center">
                    <Flame className="w-7 h-7 text-red-500 animate-pulse" />
                  </div>
                </div>

                {/* Loading Messages */}
                <h3 className="text-xl font-bold text-white mb-2 font-display">
                  Scanning dump.cs...
                </h3>
                <p className="text-sm text-slate-400 font-medium mb-6 animate-pulse">
                  Please wait...
                </p>

                {/* Smooth Progress Bar */}
                <div className="space-y-2 max-w-xs mx-auto">
                  <div className="w-full bg-red-950/20 h-2 rounded-full overflow-hidden border border-red-500/10 p-[1px]">
                    <div 
                      className="bg-gradient-to-r from-red-600 to-red-500 h-full rounded-full transition-all duration-150 shadow-[0_0_10px_#EF4444]"
                      style={{ width: `${bulkScanProgress}%` }}
                    ></div>
                  </div>
                  <div className="flex justify-between items-center text-[10px] font-mono text-slate-500 uppercase tracking-widest font-bold">
                    <span>STATUS: PARSING</span>
                    <span className="text-red-400 font-bold">{bulkScanProgress}%</span>
                  </div>
                </div>

                <div className="absolute bottom-4 left-0 right-0 text-[9px] text-slate-600 font-mono uppercase tracking-widest text-center pointer-events-none">
                  Do not reload page during operation
                </div>
              </div>
            </motion.div>
          )}

          {/* VIEW 3: MAIN RESULTS DASHBOARD */}
          {activeTab === 'mapper' && view === 'results' && (
            <motion.div
              key="results-view"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.25 }}
              className="space-y-6"
            >
              
              {/* Dashboard Action Toolbar */}
              <div className="bg-[#0d0d14]/80 backdrop-blur-md border border-red-950/30 rounded-2xl p-4 flex flex-col md:flex-row items-center justify-between gap-4 shadow-xl">
                <div className="flex items-center gap-3 w-full md:w-auto">
                  <div className="p-2 bg-red-950/20 border border-red-500/20 rounded-xl">
                    <FileCode className="w-5 h-5 text-red-500" />
                  </div>
                  <div className="truncate">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-bold text-white font-mono truncate max-w-[200px] sm:max-w-xs">{fileName}</span>
                      {isDemo && (
                        <span className="text-[9px] bg-red-500/10 text-red-400 border border-red-500/25 px-2 py-0.5 rounded font-mono uppercase font-bold tracking-widest">SANDBOX</span>
                      )}
                    </div>
                    <p className="text-[10px] text-slate-500 font-mono mt-0.5">SIZE: {formattedFileSize} • LINES: {lineCount.toLocaleString()}</p>
                  </div>
                </div>

                <div className="flex flex-wrap items-center gap-2.5 w-full md:w-auto justify-end">
                  <button
                    onClick={triggerFileBrowser}
                    className="flex-1 sm:flex-none px-4 py-2 bg-slate-900 border border-red-500/20 hover:border-red-500/40 hover:bg-red-950/10 text-red-400 hover:text-red-300 text-xs font-bold font-display rounded-xl tracking-wider uppercase transition-all cursor-pointer flex items-center justify-center gap-1.5"
                  >
                    <Upload className="w-3.5 h-3.5" /> UPLOAD NEW
                  </button>
                  <button
                    onClick={() => copyToClipboard(getFormattedResultsText(), 'all-features')}
                    className="flex-1 sm:flex-none px-4 py-2 bg-gradient-to-r from-red-600 to-red-500 hover:from-red-500 hover:to-red-400 text-white text-xs font-bold font-display rounded-xl tracking-wider uppercase transition-all shadow-[0_0_15px_rgba(239,68,68,0.25)] cursor-pointer flex items-center justify-center gap-1.5"
                  >
                    {copiedId === 'all-features' ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-white" />
                        <span>COPIED ALL RESULTS!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 text-white" />
                        <span>COPY ALL RESULTS</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={handleClear}
                    className="px-3 py-2 bg-zinc-950 border border-slate-800 text-slate-400 hover:text-red-400 hover:border-red-500/30 rounded-xl text-xs font-bold tracking-wider transition-all cursor-pointer"
                    title="Clear system state"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {/* Main Content Sections split: Search & results listing */}
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
                
                {/* LEFT LIST PANEL: grid of mapped RVA values (Col 9) */}
                <div className="lg:col-span-9 space-y-6">
                  
                  {/* Search bar & view toggle row */}
                  <div className="bg-[#0d0d14]/80 backdrop-blur-md border border-red-950/30 rounded-2xl p-4.5 shadow-xl flex flex-col md:flex-row items-center justify-between gap-4">
                    <div className="relative w-full md:max-w-md">
                      <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4.5 h-4.5 text-slate-500" />
                      <input 
                        type="text"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        placeholder="Search predefined features (e.g. FPS, Gun, Ammo)..."
                        className="w-full bg-[#050508] border border-red-950/40 focus:border-red-500 rounded-xl pl-11 pr-14 py-2.5 text-xs text-white placeholder-slate-600 outline-none transition-all font-mono select-text"
                        autoComplete="off"
                        autoCorrect="off"
                        autoCapitalize="none"
                        spellCheck="false"
                      />
                      {searchQuery && (
                        <button 
                          onClick={() => setSearchQuery('')}
                          className="absolute right-4 top-1/2 -translate-y-1/2 text-[10px] uppercase font-bold text-slate-500 hover:text-red-400 font-mono cursor-pointer"
                        >
                          Clear
                        </button>
                      )}
                    </div>

                    <div className="flex items-center gap-3 w-full md:w-auto justify-end">
                      <div className="flex items-center gap-1.5 bg-[#050508] border border-red-950/40 p-1 rounded-xl">
                        <button
                          onClick={() => setResultsLayout('cards')}
                          className={`px-3 py-1.5 rounded-lg text-[10px] font-bold font-display tracking-widest transition-all cursor-pointer flex items-center gap-1 ${
                            resultsLayout === 'cards'
                              ? 'bg-red-500/10 border border-red-500/20 text-red-400'
                              : 'text-slate-500 hover:text-slate-300'
                          }`}
                        >
                          <Grid className="w-3 h-3" /> CARDS
                        </button>
                        <button
                          onClick={() => setResultsLayout('plain')}
                          className={`px-3 py-1.5 rounded-lg text-[10px] font-bold font-display tracking-widest transition-all cursor-pointer flex items-center gap-1 ${
                            resultsLayout === 'plain'
                              ? 'bg-red-500/10 border border-red-500/20 text-red-400'
                              : 'text-slate-500 hover:text-slate-300'
                          }`}
                        >
                          <Terminal className="w-3 h-3" /> PLAIN TEXT
                        </button>
                      </div>
                    </div>
                  </div>

                  {/* RESULTS CONTAINER */}
                  {resultsLayout === 'cards' ? (
                    <div>
                      {/* Section Header */}
                      <div className="flex items-center justify-between border-b border-red-950/20 pb-3 mb-4">
                        <h3 className="text-xs font-bold tracking-widest uppercase font-display text-red-400">FUNCTION</h3>
                        <span className="text-[10px] bg-red-950/20 border border-red-500/25 px-2 py-0.5 rounded-md font-mono text-red-400 font-bold">
                          {filteredFeatures.length} FEATURES SHOWING
                        </span>
                      </div>

                      {filteredFeatures.length === 0 ? (
                        <div className="bg-[#0d0d14]/50 border border-red-950/20 rounded-2xl py-16 text-center text-slate-500">
                          <Search className="w-10 h-10 mx-auto mb-3 text-slate-600 animate-pulse" />
                          <p className="text-xs uppercase font-bold tracking-widest text-slate-400">No Match Found</p>
                          <p className="text-[11px] text-slate-500 mt-1">Try adjusting your search filters</p>
                        </div>
                      ) : (
                        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                          {filteredFeatures.map((feature, index) => {
                            const rva = bulkScanResults[feature] || 'Not Found';
                            const isFound = rva !== 'Not Found';
                            const mapping = SMART_MAPPINGS.find(m => m.feature === feature);
                            const isClickableType = isFound && mapping && ['bool', 'int', 'float'].includes(mapping.type);

                            return (
                              <motion.div
                                key={`card-${feature}-${index}`}
                                initial={{ opacity: 0, scale: 0.98 }}
                                animate={{ opacity: 1, scale: 1 }}
                                transition={{ duration: 0.2 }}
                                onClick={() => {
                                  if (isClickableType) {
                                    const { body, funcName } = getFunctionBodyForFeature(feature, rva, fileContent);
                                    setSelectedFeatureForModal(feature);
                                    setModalFunctionBody(body);
                                    setModalRva(rva);
                                    setModalType(mapping.type);
                                    setModalFuncName(funcName);
                                  } else {
                                    copyToClipboard(rva, `card-rva-${index}`);
                                  }
                                }}
                                className={`bg-[#0d0d14]/80 border rounded-2xl p-5 flex flex-col justify-between gap-4 cursor-pointer relative group transition-all duration-350 overflow-hidden ${
                                  isFound 
                                    ? isClickableType 
                                      ? 'border-red-950/40 hover:border-red-500/60 hover:bg-red-500/10 hover:shadow-[0_0_25px_rgba(239,68,68,0.12)]' 
                                      : 'border-red-950/40 hover:border-red-500/40 hover:bg-red-500/5 hover:shadow-[0_0_20px_rgba(239,68,68,0.06)]' 
                                    : 'border-slate-900 opacity-60 hover:opacity-100 hover:border-red-500/10'
                                }`}
                              >
                                <div className="flex items-start justify-between gap-3">
                                  <div>
                                    <h4 className="text-xs font-bold text-white tracking-wide group-hover:text-red-400 transition-colors font-display">
                                      {feature}
                                    </h4>
                                    <span className="text-[9px] uppercase font-mono tracking-widest text-slate-600 mt-1 block">IDENTIFIED ATTRIBUTE</span>
                                  </div>
                                  <div className="flex flex-col items-end gap-1 shrink-0">
                                    <span className={`text-[9px] font-mono px-2 py-0.5 border rounded-md font-bold uppercase transition-all ${
                                      isFound && mapping ? (
                                        mapping.type === 'bool' ? 'bg-rose-500/10 border-rose-500/25 text-rose-400' :
                                        mapping.type === 'int' ? 'bg-blue-500/10 border-blue-500/25 text-blue-400' :
                                        mapping.type === 'float' ? 'bg-amber-500/10 border-amber-500/25 text-amber-400' :
                                        'bg-red-500/10 border-red-500/20 text-red-400'
                                      ) : 'bg-slate-900 border-slate-800 text-slate-500'
                                    }`}>
                                      {isFound && mapping ? mapping.type : 'FUNC'}
                                    </span>
                                  </div>
                                </div>

                                <div className="border-t border-red-950/15 pt-3 flex items-center justify-between">
                                  <span className={`text-[10px] font-mono transition-colors ${
                                    isClickableType ? 'text-red-400 font-bold group-hover:text-red-300' : 'text-slate-500'
                                  }`}>
                                    {isClickableType ? 'VIEW CODE ➔' : 'RVA:'}
                                  </span>
                                  <span className={`text-xs font-bold font-mono tracking-wide ${
                                    isFound 
                                      ? 'text-red-400 group-hover:text-red-300 drop-shadow-[0_0_6px_rgba(239,68,68,0.2)]' 
                                      : 'text-slate-600'
                                  }`}>
                                    {rva}
                                  </span>
                                </div>

                                {/* Copied message notification badge */}
                                <AnimatePresence>
                                  {copiedId === `card-rva-${index}` && (
                                    <motion.div 
                                      initial={{ opacity: 0, y: 10 }}
                                      animate={{ opacity: 1, y: 0 }}
                                      exit={{ opacity: 0, y: -10 }}
                                      className="absolute inset-0 bg-[#0d0d14]/95 backdrop-blur-sm flex items-center justify-center gap-2 z-10"
                                    >
                                      <Check className="w-4 h-4 text-red-500" />
                                      <span className="text-xs font-bold text-red-400 font-display uppercase tracking-wider">COPIED RVA</span>
                                    </motion.div>
                                  )}
                                </AnimatePresence>
                              </motion.div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  ) : (
                    <div className="bg-[#050508] border border-red-950/30 rounded-2xl p-5 shadow-2xl relative">
                      <div className="flex justify-between items-center pb-3 mb-4 border-b border-red-950/20">
                        <span className="text-[10px] font-mono uppercase tracking-widest text-slate-500">RAW TERMINAL DISPLAY (FUNCTION ONLY)</span>
                        <button
                          onClick={() => copyToClipboard(getFormattedResultsText(searchQuery), 'plain-raw-box')}
                          className="text-[10px] font-mono font-bold bg-slate-900 border border-red-500/20 hover:border-red-500/40 text-red-400 hover:text-red-300 px-3 py-1.5 rounded-lg transition-all cursor-pointer flex items-center gap-1.5"
                        >
                          {copiedId === 'plain-raw-box' ? 'COPIED!' : 'COPY'}
                        </button>
                      </div>
                      <pre className="text-slate-300 font-mono text-[11px] sm:text-xs overflow-x-auto whitespace-pre leading-relaxed p-4 bg-[#08080c] rounded-xl border border-red-950/20 max-h-[500px] select-text">
                        {getFormattedResultsText(searchQuery)}
                      </pre>
                    </div>
                  )}

                </div>

                {/* RIGHT SYSTEM PANEL: details & diagnostics (Col 3) */}
                <div className="lg:col-span-3 space-y-6">
                  
                  {/* Scan Info Widget */}
                  <div className="bg-[#0d0d14]/80 backdrop-blur-md border border-red-950/30 rounded-2xl p-5 shadow-xl">
                    <h3 className="text-xs font-bold tracking-widest uppercase text-white font-display border-b border-red-950/20 pb-3 mb-4 flex items-center gap-1.5">
                      <Flame className="w-4 h-4 text-red-500" /> METRIC REPORT
                    </h3>

                    <div className="space-y-4 font-mono text-[11px]">
                      <div className="bg-[#050508] p-3 rounded-xl border border-red-950/20">
                        <span className="text-slate-500 text-[10px] uppercase block tracking-wider font-semibold">Active Offsets</span>
                        <span className="text-sm font-bold text-white">
                          {Object.values(bulkScanResults).filter(v => v !== 'Not Found').length} / {UNIQUE_FEATURES.length} FOUND
                        </span>
                      </div>
                      <div className="bg-[#050508] p-3 rounded-xl border border-red-950/20">
                        <span className="text-slate-500 text-[10px] uppercase block tracking-wider font-semibold">Scan Duration</span>
                        <span className="text-sm font-bold text-red-400">{bulkScanTime} ms</span>
                      </div>
                      <div className="bg-[#050508] p-3 rounded-xl border border-red-950/20">
                        <span className="text-slate-500 text-[10px] uppercase block tracking-wider font-semibold">Security Integrity</span>
                        <span className="text-[11px] text-green-500 font-bold flex items-center gap-1 mt-1">
                          ✓ SECURED CLIENT-SIDE
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* System Explainer */}
                  <div className="bg-[#0d0d14]/80 backdrop-blur-md border border-red-950/30 rounded-2xl p-5 shadow-xl">
                    <h3 className="text-xs font-bold tracking-widest uppercase text-white font-display border-b border-red-950/20 pb-3 mb-3">
                      SYSTEM TIPS
                    </h3>
                    <p className="text-slate-400 text-xs leading-relaxed space-y-2">
                      Click any card to automatically copy its extracted RVA offset directly into your computer clipboard. Use plain text view for batch copying mappings.
                    </p>
                  </div>

                </div>

              </div>
            </motion.div>
          )}

          {/* VIEW 4: LIBIL2CPP HEX VIEWER TAB */}
          {activeTab === 'hexViewer' && (
            <motion.div
              key="hex-viewer-view"
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -15 }}
              transition={{ duration: 0.25, ease: 'easeOut' }}
              className="max-w-4xl w-full mx-auto space-y-6 select-none"
            >
              {/* Header Info Banner */}
              <div className="bg-[#0d0d14]/90 backdrop-blur-xl border border-red-950/30 rounded-3xl p-6 md:p-8 relative overflow-hidden shadow-2xl">
                <div className="absolute top-0 right-0 w-[150px] h-[150px] bg-red-600/5 blur-[50px] pointer-events-none rounded-full" />
                
                <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
                  <div>
                    <h2 className="text-2xl font-bold tracking-tight text-white mb-2 font-display flex items-center gap-3">
                      <Binary className="w-7 h-7 text-red-500" />
                      LIBIL2CPP HEX VIEWER
                    </h2>
                    <p className="text-xs md:text-sm text-slate-400 max-w-xl leading-relaxed">
                      Securely parse binary bytes of your uploaded <span className="text-red-400 font-mono font-semibold">libil2cpp.so</span> file completely client-side. Jump to specific memory offsets instantly.
                    </p>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <button
                      onClick={handleHexClear}
                      className="px-4 py-2 border border-red-500/20 hover:border-red-500/40 bg-red-950/10 hover:bg-red-950/30 text-red-400 hover:text-red-300 rounded-xl text-xs font-bold tracking-wider font-display transition-all cursor-pointer flex items-center gap-1.5 uppercase"
                    >
                      <Trash2 className="w-3.5 h-3.5" /> Clear
                    </button>
                    <button
                      onClick={() => setActiveTab('mapper')}
                      className="px-4 py-2 bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-red-500/30 text-slate-300 hover:text-white rounded-xl text-xs font-bold tracking-wider font-display transition-all cursor-pointer flex items-center gap-1.5 uppercase"
                    >
                      <ArrowLeft className="w-3.5 h-3.5" /> Back
                    </button>
                  </div>
                </div>
              </div>

              {/* Error Alert Display */}
              {hexError && (
                <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-2xl text-red-400 text-xs font-semibold flex items-center gap-2.5 shadow-lg animate-pulse select-text">
                  <X className="w-4 h-4 shrink-0 cursor-pointer" onClick={() => setHexError('')} />
                  <span>{hexError}</span>
                </div>
              )}

              {/* Upload & Offset Controls Row */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* 1. Drag & Drop Upload Card */}
                <div 
                  onDragOver={handleHexDragOver}
                  onDragLeave={handleHexDragLeave}
                  onDrop={handleHexDrop}
                  className={`bg-[#0d0d14]/90 backdrop-blur-xl border rounded-3xl p-6 text-center relative overflow-hidden transition-all duration-300 shadow-2xl flex flex-col justify-center min-h-[220px] ${
                    isHexDragging 
                      ? 'border-red-500 bg-red-500/5 shadow-[0_0_40px_rgba(239,68,68,0.15)] scale-[1.01]' 
                      : 'border-red-950/30 hover:border-red-500/20'
                  }`}
                >
                  {/* Drag overlay */}
                  {isHexDragging && (
                    <div className="absolute inset-0 bg-[#08080c]/90 z-20 flex flex-col items-center justify-center transition-opacity duration-300 pointer-events-none">
                      <Upload className="w-10 h-10 text-red-500 mb-2 animate-bounce" />
                      <p className="text-sm font-bold text-red-400 font-display">Drop libil2cpp.so file here</p>
                    </div>
                  )}

                  {!hexUploadSuccess ? (
                    <div className="space-y-4">
                      <div className="w-12 h-12 bg-red-950/20 border border-red-500/20 rounded-xl flex items-center justify-center mx-auto shadow-[0_0_15px_rgba(239,68,68,0.05)]">
                        <Upload className="w-5.5 h-5.5 text-red-500" />
                      </div>
                      <div>
                        <h3 className="text-sm font-bold text-white font-display uppercase tracking-wider">Select libil2cpp.so</h3>
                        <p className="text-[11px] text-slate-500 mt-1 max-w-xs mx-auto">
                          Drag and drop or browse to load file. Processed fully offline.
                        </p>
                      </div>
                      <div>
                        <button
                          onClick={triggerHexFileBrowser}
                          className="px-5 py-2.5 bg-gradient-to-r from-red-600 to-red-500 hover:from-red-500 hover:to-red-400 text-white font-bold font-display text-[10px] rounded-lg shadow-[0_0_15px_rgba(239,68,68,0.2)] hover:scale-[1.02] transition-all cursor-pointer uppercase tracking-wider"
                        >
                          Upload File
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      <div className="w-12 h-12 bg-emerald-950/20 border border-emerald-500/20 rounded-xl flex items-center justify-center mx-auto shadow-[0_0_15px_rgba(16,185,129,0.05)]">
                        <Check className="w-5.5 h-5.5 text-emerald-500" />
                      </div>
                      <div>
                        <span className="text-[10px] bg-emerald-500/10 text-emerald-400 border border-emerald-500/25 px-2 py-0.5 rounded font-mono uppercase font-bold tracking-widest">
                          Upload Successful
                        </span>
                        <h3 className="text-sm font-mono font-bold text-white mt-2.5 truncate max-w-[250px] mx-auto">
                          {hexFileName}
                        </h3>
                        <p className="text-[10px] text-slate-500 font-mono mt-0.5">
                          SIZE: {formattedHexFileSize}
                        </p>
                      </div>
                      <div>
                        <button
                          onClick={triggerHexFileBrowser}
                          className="text-[10px] font-bold uppercase tracking-wider font-display bg-red-950/15 hover:bg-red-950/35 border border-red-500/20 text-red-400 py-1.5 px-3 rounded-lg transition-all cursor-pointer"
                        >
                          Replace File
                        </button>
                      </div>
                    </div>
                  )}

                  <input 
                    type="file" 
                    ref={hexFileInputRef} 
                    onChange={handleHexFileChange} 
                    accept=".so" 
                    className="hidden" 
                  />
                </div>

                {/* 2. Jump to Offset Input Card */}
                <div className="bg-[#0d0d14]/90 backdrop-blur-xl border border-red-950/30 rounded-3xl p-6 shadow-2xl flex flex-col justify-between min-h-[220px]">
                  <div className="space-y-4">
                    <h3 className="text-xs font-bold tracking-widest uppercase text-red-400 font-display flex items-center gap-2">
                      <Terminal className="w-4 h-4 text-red-500" />
                      JUMP TO FILE OFFSET
                    </h3>
                    <p className="text-[11px] text-slate-500 leading-relaxed">
                      Input the hexadecimal target offset from dump.cs (e.g. <span className="text-slate-400 font-mono">0x7F17870</span> or <span className="text-slate-400 font-mono">7F17870</span>). The system automatically handles prefixes.
                    </p>
                    
                    <div className="relative">
                      <div className="absolute left-3.5 top-1/2 -translate-y-1/2 text-red-500 font-mono font-bold text-xs">
                        0x
                      </div>
                      <input
                        type="text"
                        placeholder="7F17870"
                        value={hexOffsetInput.toLowerCase().startsWith('0x') ? hexOffsetInput.slice(2) : hexOffsetInput}
                        onChange={(e) => {
                          const val = e.target.value.trim();
                          setHexOffsetInput(val);
                        }}
                        className="w-full bg-[#050508] border border-red-950/20 rounded-xl py-3 pl-9 pr-4 text-xs font-mono text-slate-200 placeholder-slate-600 focus:outline-none focus:border-red-500/40 transition-all uppercase tracking-widest"
                      />
                    </div>
                  </div>

                  <div className="pt-4">
                    <button
                      onClick={handleReadHex}
                      disabled={!hexUploadSuccess || !hexOffsetInput}
                      className={`w-full py-3 text-center text-xs font-bold font-display rounded-xl tracking-wider uppercase transition-all flex items-center justify-center gap-2 ${
                        hexUploadSuccess && hexOffsetInput
                          ? 'bg-gradient-to-r from-red-600 to-red-500 hover:from-red-500 hover:to-red-400 text-white cursor-pointer shadow-[0_0_20px_rgba(239,68,68,0.25)] hover:scale-[1.01]'
                          : 'bg-slate-900 border border-slate-800 text-slate-600 cursor-not-allowed'
                      }`}
                    >
                      <Binary className="w-4 h-4" />
                      <span>Read File Segment</span>
                    </button>
                  </div>
                </div>

              </div>

              {/* Hex Output Terminal Card */}
              {hexBytes && (
                <div className="bg-[#0d0d14]/90 backdrop-blur-xl border border-red-950/30 rounded-3xl p-6 shadow-2xl space-y-4">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-red-950/20 pb-4">
                    <div>
                      <h3 className="text-xs font-bold tracking-widest uppercase text-red-400 font-display flex items-center gap-2">
                        <Terminal className="w-4 h-4 text-red-500 animate-pulse" />
                        HEX DATA OUTPUT (128 BYTES)
                      </h3>
                      <p className="text-[10px] text-slate-500 font-mono mt-0.5 select-text">
                        OFFSET: 0x{(hexOffsetInput.toLowerCase().startsWith('0x') ? hexOffsetInput.slice(2) : hexOffsetInput).toUpperCase()} • SIZE: 128 BYTES (16 PER ROW)
                      </p>
                    </div>
                    
                    <div className="flex flex-wrap items-center gap-2">
                      <button
                        onClick={handleCopySelectedHex}
                        className="text-[10px] font-bold uppercase tracking-wider font-display bg-red-950/20 hover:bg-red-900/30 border border-red-500/20 hover:border-red-500/40 text-red-400 hover:text-red-300 py-1.5 px-3 rounded-lg transition-all cursor-pointer flex items-center gap-1.5"
                      >
                        {hexCopiedFeedback === 'selected' ? (
                          <>
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                            <span className="text-emerald-400">Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3.5 h-3.5" />
                            <span>Copy Selected</span>
                          </>
                        )}
                      </button>

                      <button
                        onClick={handleCopyAllHex}
                        className="text-[10px] font-bold uppercase tracking-wider font-display bg-red-950/20 hover:bg-red-900/30 border border-red-500/20 hover:border-red-500/40 text-red-400 hover:text-red-300 py-1.5 px-3 rounded-lg transition-all cursor-pointer flex items-center gap-1.5"
                      >
                        {hexCopiedFeedback === 'all' ? (
                          <>
                            <Check className="w-3.5 h-3.5 text-emerald-400" />
                            <span className="text-emerald-400">All Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3.5 h-3.5" />
                            <span>Copy All</span>
                          </>
                        )}
                      </button>
                    </div>
                  </div>

                  {/* Hex Output Box */}
                  <div className="bg-[#050508] border border-red-950/40 rounded-2xl p-6 font-mono text-sm sm:text-base md:text-lg leading-relaxed text-red-400 select-text overflow-x-auto shadow-inner relative group">
                    <pre className="whitespace-pre-wrap select-text selection:bg-red-500/30 selection:text-red-100 uppercase tracking-widest font-mono">
                      {formattedHexRows.join('\n')}
                    </pre>
                  </div>

                  <div className="text-[10px] text-slate-500 font-mono flex items-center justify-between">
                    <span>SELECTION MODE: ACTIVE</span>
                    <span>DRAG CURSOR OVER BYTES TO HIGHLIGHT</span>
                  </div>
                </div>
              )}

            </motion.div>
          )}

        </AnimatePresence>

      </main>

      {/* Footer bar */}
      <footer className="mt-auto border-t border-red-950/20 bg-[#0d0d12]/50 py-5 px-6 flex flex-col sm:flex-row justify-between items-center gap-4 text-[10px] text-slate-600 font-mono uppercase tracking-widest">
        <div className="flex flex-wrap justify-center gap-6">
          <span>PIPELINE: SINGLE-SECTION FUNCTION</span>
          <span>SYSTEM ENGINE: STABILIZED</span>
          <span>BUFFER: CACHED-MEMORY</span>
        </div>
        <div className="text-center sm:text-right">
          CLIENT EXECUTED ONLY • LOCAL DUMP PARSER
        </div>
      </footer>

      {/* DETAILS PANEL / MODAL */}
      <AnimatePresence>
        {selectedFeatureForModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/85 backdrop-blur-md z-50 flex items-center justify-center p-4 sm:p-6 md:p-10"
            onClick={() => setSelectedFeatureForModal(null)}
          >
            <motion.div
              initial={{ scale: 0.95, y: 20, opacity: 0 }}
              animate={{ scale: 1, y: 0, opacity: 1 }}
              exit={{ scale: 0.95, y: 20, opacity: 0 }}
              transition={{ type: 'spring', duration: 0.4 }}
              className="bg-[#09090d] border border-red-500/30 rounded-2xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-[0_0_50px_rgba(239,68,68,0.15)] overflow-hidden"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Header */}
              <div className="border-b border-red-950/25 p-5 flex items-start justify-between bg-[#0e0e14]/90">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className={`text-[9px] font-mono px-2 py-0.5 border rounded-md font-bold uppercase ${
                      modalType === 'bool' ? 'bg-[#ff0055]/10 border-[#ff0055]/25 text-[#ff4477]' :
                      modalType === 'int' ? 'bg-[#0077ff]/10 border-[#0077ff]/25 text-[#4499ff]' :
                      modalType === 'float' ? 'bg-[#ffaa00]/10 border-[#ffaa00]/25 text-[#ffcc44]' :
                      'bg-red-500/10 border-red-500/20 text-red-400'
                    }`}>
                      {modalType.toUpperCase()}
                    </span>
                    <h3 className="text-sm sm:text-base font-bold text-white font-display tracking-wide">
                      {selectedFeatureForModal}
                    </h3>
                  </div>
                  <p className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">
                    FUNCTION DETECTED: <span className="text-red-400/80 font-bold">{modalFuncName}</span>
                  </p>
                </div>
                
                <button
                  onClick={() => setSelectedFeatureForModal(null)}
                  className="bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:border-red-500/40 p-2 rounded-xl transition-all cursor-pointer"
                  id="close-modal-btn"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Code Area */}
              <div className="flex-1 overflow-y-auto p-6 bg-[#040407] border-b border-red-950/20 custom-scrollbar select-text">
                {modalFunctionBody ? (
                  <div className="relative group/code">
                    <pre className="font-mono text-xs sm:text-[13px] leading-relaxed whitespace-pre-wrap select-text p-4 rounded-xl bg-[#07070b] border border-red-950/15 min-h-[120px] overflow-auto">
                      {highlightCSharp(modalFunctionBody)}
                    </pre>
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center py-12 text-slate-500 font-mono text-xs">
                    <Terminal className="w-8 h-8 text-slate-600 mb-2 animate-pulse" />
                    <span>COULD NOT LOCATE FUNCTION BODY IN FILE</span>
                  </div>
                )}

                {/* Boolean Patch Values */}
                {modalType === 'bool' && (
                  <div className="mt-6 border-t border-red-950/30 pt-6 space-y-4">
                    <h4 className="text-xs font-bold tracking-widest uppercase text-red-400 font-display flex items-center gap-2">
                      <Terminal className="w-3.5 h-3.5 text-red-500 animate-pulse" />
                      BOOLEAN PATCH VALUES
                    </h4>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      {/* TRUE Patch */}
                      <div className="bg-[#07070b] border border-red-950/20 rounded-xl p-4 flex flex-col justify-between gap-3 relative group/patch">
                        <div>
                          <div className="text-[10px] font-bold font-display tracking-widest text-emerald-400 mb-2 uppercase">
                            TRUE
                          </div>
                          <code className="block font-mono text-xs bg-slate-950/50 p-2.5 rounded-lg border border-slate-900 text-slate-300 break-all select-all">
                            01 00 A0 E3 1E FF 2F E1
                          </code>
                        </div>
                        <button
                          onClick={() => {
                            navigator.clipboard.writeText('01 00 A0 E3 1E FF 2F E1');
                            setModalCopiedType('true');
                            setTimeout(() => setModalCopiedType(null), 1500);
                          }}
                          className="w-full text-[10px] font-bold uppercase tracking-wider font-display bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-red-500/30 text-slate-300 hover:text-white py-2 px-3 rounded-lg transition-all cursor-pointer flex items-center justify-center gap-1.5"
                        >
                          {modalCopiedType === 'true' ? (
                            <>
                              <Check className="w-3 h-3 text-emerald-400" />
                              <span className="text-emerald-400">Copied!</span>
                            </>
                          ) : (
                            <>
                              <Copy className="w-3 h-3" />
                              <span>Copy TRUE</span>
                            </>
                          )}
                        </button>
                      </div>

                      {/* FALSE Patch */}
                      <div className="bg-[#07070b] border border-red-950/20 rounded-xl p-4 flex flex-col justify-between gap-3 relative group/patch">
                        <div>
                          <div className="text-[10px] font-bold font-display tracking-widest text-rose-400 mb-2 uppercase">
                            FALSE
                          </div>
                          <code className="block font-mono text-xs bg-slate-950/50 p-2.5 rounded-lg border border-slate-900 text-slate-300 break-all select-all">
                            00 00 A0 E3 1E FF 2F E1
                          </code>
                        </div>
                        <button
                          onClick={() => {
                            navigator.clipboard.writeText('00 00 A0 E3 1E FF 2F E1');
                            setModalCopiedType('false');
                            setTimeout(() => setModalCopiedType(null), 1500);
                          }}
                          className="w-full text-[10px] font-bold uppercase tracking-wider font-display bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-red-500/30 text-slate-300 hover:text-white py-2 px-3 rounded-lg transition-all cursor-pointer flex items-center justify-center gap-1.5"
                        >
                          {modalCopiedType === 'false' ? (
                            <>
                              <Check className="w-3 h-3 text-rose-400" />
                              <span className="text-rose-400">Copied!</span>
                            </>
                          ) : (
                            <>
                              <Copy className="w-3 h-3" />
                              <span>Copy FALSE</span>
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                )}

                {/* Integer Patch Values */}
                {modalType === 'int' && (
                  <div className="mt-6 border-t border-red-950/30 pt-6 space-y-4">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                      <h4 className="text-xs font-bold tracking-widest uppercase text-red-400 font-display flex items-center gap-2">
                        <Terminal className="w-3.5 h-3.5 text-red-500 animate-pulse" />
                        INTEGER PATCH VALUES
                      </h4>
                      <button
                        onClick={() => {
                          const allText = filteredIntPatchValues.map(v => `${v.decimal}: ${v.hex}`).join('\n');
                          navigator.clipboard.writeText(allText);
                          setModalCopiedType('int_all');
                          setTimeout(() => setModalCopiedType(null), 1500);
                        }}
                        className="self-start sm:self-auto text-[10px] font-bold uppercase tracking-wider font-display bg-red-950/20 hover:bg-red-900/30 border border-red-500/20 hover:border-red-500/40 text-red-400 hover:text-red-300 py-1.5 px-3 rounded-lg transition-all cursor-pointer flex items-center gap-1.5"
                      >
                        {modalCopiedType === 'int_all' ? (
                          <>
                            <Check className="w-3 h-3 text-emerald-400" />
                            <span className="text-emerald-400">All Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3 h-3" />
                            <span>Copy All</span>
                          </>
                        )}
                      </button>
                    </div>

                    {/* Filter search box */}
                    <div className="relative">
                      <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-500" />
                      <input
                        type="text"
                        placeholder="Filter by decimal value... (e.g., 100, 255)"
                        value={intSearchQuery}
                        onChange={(e) => setIntSearchQuery(e.target.value)}
                        className="w-full bg-[#07070b] border border-red-950/20 rounded-xl py-2 pl-9 pr-8 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-red-500/40 transition-all font-sans"
                      />
                      {intSearchQuery && (
                        <button
                          onClick={() => setIntSearchQuery('')}
                          className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300 transition-colors cursor-pointer"
                        >
                          <X className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>

                    {/* Table View */}
                    <div className="bg-[#07070b] border border-red-950/15 rounded-xl overflow-hidden shadow-inner">
                      <div className="max-h-[300px] overflow-y-auto custom-scrollbar">
                        <table className="w-full text-left border-collapse">
                          <thead className="bg-[#0a0a0f] text-[10px] font-bold font-display tracking-widest text-slate-400 border-b border-red-950/15 sticky top-0 z-10">
                            <tr>
                              <th className="py-2.5 px-4">DECIMAL VALUE</th>
                              <th className="py-2.5 px-4">HEX PATTERN</th>
                              <th className="py-2.5 px-4 text-right">ACTION</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-red-950/10 font-mono text-[11px]">
                            {filteredIntPatchValues.length > 0 ? (
                              filteredIntPatchValues.map((item, idx) => (
                                <tr key={idx} className="hover:bg-red-500/[0.02] transition-colors group/row">
                                  <td className="py-2 px-4 text-slate-200 font-semibold">{item.decimal}</td>
                                  <td className="py-2 px-4 text-red-400/90 tracking-wide select-all break-all sm:break-normal">{item.hex}</td>
                                  <td className="py-2 px-4 text-right">
                                    <button
                                      onClick={() => {
                                        navigator.clipboard.writeText(item.hex);
                                        setModalCopiedType(`int_${idx}`);
                                        setTimeout(() => setModalCopiedType(null), 1500);
                                      }}
                                      className="inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider font-display bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-red-500/30 text-slate-300 hover:text-white py-1 px-2.5 rounded-md transition-all cursor-pointer"
                                    >
                                      {modalCopiedType === `int_${idx}` ? (
                                        <>
                                          <Check className="w-3 h-3 text-emerald-400" />
                                          <span className="text-emerald-400">Copied</span>
                                        </>
                                      ) : (
                                        <>
                                          <Copy className="w-3 h-3" />
                                          <span>Copy</span>
                                        </>
                                      )}
                                    </button>
                                  </td>
                                </tr>
                              ))
                            ) : (
                              <tr>
                                <td colSpan={3} className="py-8 text-center text-slate-500 font-sans text-xs">
                                  No matching values found for "{intSearchQuery}"
                                </td>
                              </tr>
                            )}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                )}

                {/* Float Patch Values */}
                {modalType === 'float' && (
                  <div className="mt-6 border-t border-red-950/30 pt-6 space-y-4">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                      <h4 className="text-xs font-bold tracking-widest uppercase text-red-400 font-display flex items-center gap-2">
                        <Terminal className="w-3.5 h-3.5 text-red-500 animate-pulse" />
                        FLOAT PATCH VALUES
                      </h4>
                      <button
                        onClick={() => {
                          const allText = filteredFloatPatchValues.map(v => `${v.value}: ${v.hex}`).join('\n');
                          navigator.clipboard.writeText(allText);
                          setModalCopiedType('float_all');
                          setTimeout(() => setModalCopiedType(null), 1500);
                        }}
                        className="self-start sm:self-auto text-[10px] font-bold uppercase tracking-wider font-display bg-red-950/20 hover:bg-red-900/30 border border-red-500/20 hover:border-red-500/40 text-red-400 hover:text-red-300 py-1.5 px-3 rounded-lg transition-all cursor-pointer flex items-center gap-1.5"
                      >
                        {modalCopiedType === 'float_all' ? (
                          <>
                            <Check className="w-3 h-3 text-emerald-400" />
                            <span className="text-emerald-400">All Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="w-3 h-3" />
                            <span>Copy All</span>
                          </>
                        )}
                      </button>
                    </div>

                    {/* Filter search box */}
                    <div className="relative">
                      <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-500" />
                      <input
                        type="text"
                        placeholder="Filter by float value... (e.g., 1000.0, 1.0)"
                        value={floatSearchQuery}
                        onChange={(e) => setFloatSearchQuery(e.target.value)}
                        className="w-full bg-[#07070b] border border-red-950/20 rounded-xl py-2 pl-9 pr-8 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-red-500/40 transition-all font-sans"
                      />
                      {floatSearchQuery && (
                        <button
                          onClick={() => setFloatSearchQuery('')}
                          className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500 hover:text-slate-300 transition-colors cursor-pointer"
                        >
                          <X className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>

                    {/* Table View */}
                    <div className="bg-[#07070b] border border-red-950/15 rounded-xl overflow-hidden shadow-inner">
                      <div className="max-h-[300px] overflow-y-auto custom-scrollbar">
                        <table className="w-full text-left border-collapse">
                          <thead className="bg-[#0a0a0f] text-[10px] font-bold font-display tracking-widest text-slate-400 border-b border-red-950/15 sticky top-0 z-10">
                            <tr>
                              <th className="py-2.5 px-4">FLOAT VALUE</th>
                              <th className="py-2.5 px-4">HEX PATTERN</th>
                              <th className="py-2.5 px-4 text-right">ACTION</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-red-950/10 font-mono text-[11px]">
                            {filteredFloatPatchValues.length > 0 ? (
                              filteredFloatPatchValues.map((item, idx) => (
                                <tr key={idx} className="hover:bg-red-500/[0.02] transition-colors group/row">
                                  <td className="py-2 px-4 text-slate-200 font-semibold">{item.value}</td>
                                  <td className="py-2 px-4 text-red-400/90 tracking-wide select-all break-all sm:break-normal">{item.hex}</td>
                                  <td className="py-2 px-4 text-right">
                                    <button
                                      onClick={() => {
                                        navigator.clipboard.writeText(item.hex);
                                        setModalCopiedType(`float_${idx}`);
                                        setTimeout(() => setModalCopiedType(null), 1500);
                                      }}
                                      className="inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider font-display bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-red-500/30 text-slate-300 hover:text-white py-1 px-2.5 rounded-md transition-all cursor-pointer"
                                    >
                                      {modalCopiedType === `float_${idx}` ? (
                                        <>
                                          <Check className="w-3 h-3 text-emerald-400" />
                                          <span className="text-emerald-400">Copied</span>
                                        </>
                                      ) : (
                                        <>
                                          <Copy className="w-3 h-3" />
                                          <span>Copy</span>
                                        </>
                                      )}
                                    </button>
                                  </td>
                                </tr>
                              ))
                            ) : (
                              <tr>
                                <td colSpan={3} className="py-8 text-center text-slate-500 font-sans text-xs">
                                  No matching values found for "{floatSearchQuery}"
                                </td>
                              </tr>
                            )}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Action Buttons Footer */}
              <div className="p-5 bg-[#0e0e14]/90 flex flex-wrap items-center justify-between gap-3">
                {/* RVA Display */}
                <div className="bg-slate-950 border border-slate-900 rounded-xl px-4 py-2 flex items-center gap-3">
                  <span className="text-[10px] font-mono text-slate-500 uppercase tracking-wider font-semibold">RVA Offset:</span>
                  <span className="text-xs font-bold font-mono text-red-400 drop-shadow-[0_0_4px_rgba(239,68,68,0.3)]">{modalRva}</span>
                </div>

                <div className="flex items-center gap-2">
                  {/* Copy RVA */}
                  <button
                    onClick={() => {
                      navigator.clipboard.writeText(modalRva);
                      setModalCopiedType('rva');
                      setTimeout(() => setModalCopiedType(null), 1500);
                    }}
                    className="text-xs font-semibold uppercase tracking-wider font-display bg-slate-950 border border-slate-800 hover:border-red-500/30 text-slate-400 hover:text-red-300 px-4 py-2.5 rounded-xl transition-all cursor-pointer flex items-center gap-1.5"
                    id="copy-rva-btn"
                  >
                    {modalCopiedType === 'rva' ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-red-500" />
                        <span>Copied RVA!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy RVA</span>
                      </>
                    )}
                  </button>

                  {/* Copy Function */}
                  <button
                    onClick={() => {
                      navigator.clipboard.writeText(modalFunctionBody);
                      setModalCopiedType('code');
                      setTimeout(() => setModalCopiedType(null), 1500);
                    }}
                    className="text-xs font-bold uppercase tracking-wider font-display bg-red-600 hover:bg-red-500 text-white px-4 py-2.5 rounded-xl transition-all cursor-pointer flex items-center gap-1.5 shadow-[0_0_15px_rgba(220,38,38,0.3)]"
                    id="copy-func-btn"
                  >
                    {modalCopiedType === 'code' ? (
                      <>
                        <Check className="w-3.5 h-3.5" />
                        <span>Copied Code!</span>
                      </>
                    ) : (
                      <>
                        <FileCode className="w-3.5 h-3.5" />
                        <span>Copy Function</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
      
    </div>
  );
}
